export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_TEACHERS_PENDING = 'REQUEST_TEACHERS_PENDING';
export const REQUEST_TEACHERS_SUCCESS = 'REQUEST_TEACHERS_SUCCESS';
export const REQUEST_TEACHERS_FAILED = 'REQUEST_TEACHERS_FAILED';